// AUTO-GENERATED by backend/scripts/gen_audio.py — do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */
export const AUDIO: Record<string, number> = {
  "music/region_1": require("../../assets/audio/music/region_1.mp3"),
  "music/region_10": require("../../assets/audio/music/region_10.mp3"),
  "music/region_2": require("../../assets/audio/music/region_2.mp3"),
  "music/region_3": require("../../assets/audio/music/region_3.mp3"),
  "music/region_4": require("../../assets/audio/music/region_4.mp3"),
  "music/region_5": require("../../assets/audio/music/region_5.mp3"),
  "music/region_6": require("../../assets/audio/music/region_6.mp3"),
  "music/region_7": require("../../assets/audio/music/region_7.mp3"),
  "music/region_8": require("../../assets/audio/music/region_8.mp3"),
  "music/region_9": require("../../assets/audio/music/region_9.mp3"),
  "sfx/build": require("../../assets/audio/sfx/build.mp3"),
  "sfx/coin": require("../../assets/audio/sfx/coin.mp3"),
  "sfx/crit": require("../../assets/audio/sfx/crit.mp3"),
  "sfx/defeat": require("../../assets/audio/sfx/defeat.mp3"),
  "sfx/hit": require("../../assets/audio/sfx/hit.mp3"),
  "sfx/kill": require("../../assets/audio/sfx/kill.mp3"),
  "sfx/skill": require("../../assets/audio/sfx/skill.mp3"),
  "sfx/ui_tap": require("../../assets/audio/sfx/ui_tap.mp3"),
  "sfx/victory": require("../../assets/audio/sfx/victory.mp3"),
};
