// AUTO-GENERATED by backend/scripts/gen_audio.py — do not edit by hand. Music only (SFX removed by owner choice).
export const AUDIO: Record<string, number> = {
  "music/region_1": require("../../assets/audio/music/region_1.mp3"),
  "music/region_10": require("../../assets/audio/music/region_10.mp3"),
  "music/region_2": require("../../assets/audio/music/region_2.mp3"),
  "music/region_3": require("../../assets/audio/music/region_3.mp3"),
  "music/region_4": require("../../assets/audio/music/region_4.mp3"),
  "music/region_5": require("../../assets/audio/music/region_5.mp3"),
  "music/region_6": require("../../assets/audio/music/region_6.mp3"),
  "music/region_7": require("../../assets/audio/music/region_7.mp3"),
  "music/region_8": require("../../assets/audio/music/region_8.mp3"),
  "music/region_9": require("../../assets/audio/music/region_9.mp3"),
};
