// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // `.expo` is generated by the router and `vendor` holds third-party code verbatim,
    // so neither is ours to fix.
    ignores: ['dist/*', '.expo/*', 'scripts/cmd-guard/vendor/*'],
  },
]);
